/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import beans.Antropometria;
import beans.Paciente;
import controladores.AntropometriaJpaController;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author Leonardo Vasconcelos
 */
public class antropometria extends javax.swing.JFrame {
    private Paciente paciente = new Paciente();
    private Antropometria antro = new Antropometria();
    private AntropometriaJpaController antroDao;
    public int idade;
    /**
     * Creates new form antropometria
     */
    private void iniciar()
    {
                txtPeito.setEnabled(false);
        txtAbdominal.setEnabled(false);
        txtCoxa.setEnabled(false);
        txtTriceps.setEnabled(false);
        txtSubescapular.setEnabled(false);
        txtCircAbdominal.setEnabled(false);
        txtCircPerna.setEnabled(false);
        txtCircBraco.setEnabled(false);
        txtCircPanturrilha.setEnabled(false);
        txtSuprailiaca.setEnabled(false);
        txtAxiliarMedia.setEnabled(false);
        
        txtPeito.setText("0");
        txtAbdominal.setText("0");
        txtCoxa.setText("0");
        txtTriceps.setText("0");
        txtSubescapular.setText("0");
        txtCircAbdominal.setText("0");
        txtCircPerna.setText("0");
        txtCircBraco.setText("0");
        txtCircPanturrilha.setText("0");
        txtSuprailiaca.setText("0");
        txtAxiliarMedia.setText("0");
    }
    
    public antropometria(Paciente p) {
        initComponents();
        antroDao = new AntropometriaJpaController(Persistence.createEntityManagerFactory("NutriMaisPU"));
        this.paciente = p;
        lblId.setText(String.valueOf((p.getIdPaciente())));
        lblNome.setText(p.getNome());
        lblSexo.setText(p.getSexo());
        this.idade = p.getDataDeNascimento();
        this.idade = idade%10000;
        this.idade = 2016 - idade;
        
         Date d = new Date();
        SimpleDateFormat formatador = new SimpleDateFormat("ddMMyyyy");
        
        txtData.setText(formatador.format(d)); 
        
        if(p.getSexo().equals("Masculino") && this.idade>12)
        {
            cmbTipoCalculo.addItem("Tecnica Jackson e Pollock 3 Dobras");
            cmbTipoCalculo.addItem("Tecnica Jackson e Pollock 7 Dobras");
            cmbTipoCalculo.addItem("Tecnica Guedes");
            cmbTipoCalculo.addItem("Tecnica Lohman");
            cmbTipoCalculo.addItem("Tecnica Faulkner");
            cmbTipoCalculo.addItem("Tecnica Pollock");
        }else if(p.getSexo().equals("Masculino")&& this.idade<12){
            cmbTipoCalculo.addItem("Tecnica de Slaughter Maior 35MM");
            cmbTipoCalculo.addItem("Tecnica de Slaughter Menor 35MM");
            cmbTipoCalculo.addItem("Tecnica Boileau");          
        }
        
        if(p.getSexo().equals("Feminino") && this.idade>12)
        {
            cmbTipoCalculo.addItem("Tecnica Jackson e Pollock e Ward");
            cmbTipoCalculo.addItem("Tecnica Jackson e Pollock e Ward (Atletas)");
            cmbTipoCalculo.addItem("Tecnica Guedes");
        }else if(p.getSexo().equals("Feminino")&& this.idade<12){
            cmbTipoCalculo.addItem("Tecnica de Slaughter Maior 35MM");
            cmbTipoCalculo.addItem("Tecnica de Slaughter Menor 35MM");
            cmbTipoCalculo.addItem("Tecnica Boileau"); 
        }
        
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCircBraco = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtCircPerna = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        txtCircAbdominal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCoxa = new javax.swing.JTextField();
        txtAbdominal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtSubescapular = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtSuprailiaca = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtCircPanturrilha = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtTriceps = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPesoAtual = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtPesoGordura1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtPorcentagemGordura = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtAxiliarMedia = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        txtDensidadeCorporal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtimc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cmbTipoCalculo = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        txtPeito = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtClassificacaoAdequacaoPeso = new javax.swing.JTextField();
        txtAjustePesoIdeal = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtPesoMassaMagra = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtPesoIdeal = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtAdequacaoPeso = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEstatura = new javax.swing.JTextField();
        lblSexo = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(184, 225, 206));

        jLabel14.setText("Circunferência Perna:");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jLabel13.setText("Circunferência Abdomen:");

        jLabel12.setText("Coxa:");

        jLabel10.setText("Peito:");

        jLabel11.setText("Abdominal:");

        jLabel20.setText("Axiliar Média:");

        jLabel18.setText("Subescapular:");

        jLabel19.setText("Suprailíaca:");

        jLabel16.setText("Circunferência Panturrilha:");

        jLabel17.setText("Triceps:");

        jLabel15.setText("Circunferência Braço:");

        jLabel5.setText("Peso Atual:");

        txtPesoAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoAtualActionPerformed(evt);
            }
        });
        txtPesoAtual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesoAtualKeyReleased(evt);
            }
        });

        jLabel25.setText("Peso da Gordura:");

        jLabel24.setText("% de Gordura:");

        jLabel23.setText("Densidade Corporal:");

        jLabel8.setText("IMC:");

        txtimc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtimcActionPerformed(evt);
            }
        });

        jLabel9.setText("Tipo Cálculo:");

        cmbTipoCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoCalculoActionPerformed(evt);
            }
        });

        jLabel30.setText("Ajuste Peso Ideal:");

        jLabel26.setText("Peso Massa Magra:");

        jLabel27.setText("Peso Ideal:");

        jLabel28.setText("Adequação do Peso:");

        jLabel29.setText("Classificação Adequação Peso:");

        jLabel6.setText("Estatura:");

        txtEstatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstaturaActionPerformed(evt);
            }
        });
        txtEstatura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEstaturaKeyReleased(evt);
            }
        });

        lblSexo.setText("????");

        jLabel22.setText("Sexo:");

        jLabel2.setText("Nome:");

        lblNome.setText("????");

        jLabel1.setText("ID:");

        lblId.setText("????");

        jLabel7.setText("Data:");

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forms/1480533971_BT_save.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel21.setText("Instituto Federal de São Paulo");

        jLabel31.setText("Campus Capivari.");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forms/nutrimaisReduzidoReduzido.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPesoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtimc, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbTipoCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCircAbdominal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtAxiliarMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCoxa, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtAbdominal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtPeito, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtSubescapular, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtTriceps, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtSuprailiaca, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(11, 11, 11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCircBraco, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCircPerna, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCircPanturrilha, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCalcular)))
                        .addGap(196, 196, 196))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblId)
                        .addGap(172, 172, 172)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSexo)
                        .addGap(110, 110, 110))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDensidadeCorporal, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPesoMassaMagra, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPesoGordura1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPorcentagemGordura, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPesoIdeal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtAdequacaoPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtClassificacaoAdequacaoPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAjustePesoIdeal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalvar)
                            .addComponent(jLabel3))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jLabel31)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(lblId)
                    .addComponent(lblNome)
                    .addComponent(jLabel22)
                    .addComponent(lblSexo))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPesoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtimc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cmbTipoCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPeito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtTriceps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtAbdominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtSubescapular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtCoxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtSuprailiaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtCircAbdominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtAxiliarMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtCircPerna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtCircBraco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtCircPanturrilha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtDensidadeCorporal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(txtPesoMassaMagra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(txtPorcentagemGordura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addComponent(txtPesoIdeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txtPesoGordura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)
                            .addComponent(txtAdequacaoPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtClassificacaoAdequacaoPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(txtAjustePesoIdeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel21)
                .addGap(6, 6, 6)
                .addComponent(jLabel31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:        
        this.antro.setPeito(Double.parseDouble(txtPeito.getText()));
        this.antro.setAbdominal(Double.parseDouble(txtAbdominal.getText()));
        this.antro.setCoxa(Double.parseDouble(txtCoxa.getText()));
        this.antro.setTriceps(Double.parseDouble(txtTriceps.getText()));
        this.antro.setSubescapular(Double.parseDouble(txtSubescapular.getText()));
        this.antro.setCircAbdomen(Double.parseDouble(txtCircAbdominal.getText()));
        this.antro.setCircPerna(Double.parseDouble(txtCircPerna.getText()));
        this.antro.setCircBraco(Double.parseDouble(txtCircBraco.getText()));
        this.antro.setCircPanturrilha(Double.parseDouble(txtCircPanturrilha.getText()));
        this.antro.setSuprailiaca(Double.parseDouble(txtSuprailiaca.getText()));
        this.antro.setAxiliarMedia(Double.parseDouble(txtAxiliarMedia.getText()));
        
        if(this.paciente.getSexo().equals("Masculino"))
        {
            this.antro.setPesoIdeal(0);
            txtPesoIdeal.setText(String.format("%.2f", this.antro.getPesoIdeal())); 
        }
        else
        {
            this.antro.setPesoIdeal(1);
            txtPesoIdeal.setText(String.format("%.2f",this.antro.getPesoIdeal()));
        }

        
        this.antro.setAdequacaoPeso();
        txtAdequacaoPeso.setText(String.format("%.2f",this.antro.getAdequacaoPeso()));
        this.antro.setClassificacaoAdequacaoPeso();
        txtClassificacaoAdequacaoPeso.setText(this.antro.getClassificacaoAdequacaoPeso());
        this.antro.setAjustePesoIdeal();
        txtAjustePesoIdeal.setText(String.format("%.2f",this.antro.getAjustePesoIdeal()));
        
        if(cmbTipoCalculo.getSelectedItem() == "Tecnica Jackson e Pollock 3 Dobras")
        {
            this.antro.tecnicaJackPoll3dobras(this.idade);
            txtDensidadeCorporal.setText(String.format("%.2f",this.antro.getDensidadeCorporal()));
            txtPorcentagemGordura.setText(String.format("%.2f",this.antro.getPorcentagemGordura()));
            this.antro.setPesoGordura();
            txtPesoGordura1.setText(String.format("%.2f",this.antro.getPesoGordura()));
            this.antro.setPesoMassaMagra();
            txtPesoMassaMagra.setText(String.format("%.2f",this.antro.getPesoMassaMagra())); 
        } 
        if(cmbTipoCalculo.getSelectedItem() == "Tecnica Jackson e Pollock 7 Dobras")
        {
            this.antro.tecnicaJackPoll7dobras(this.idade);
            txtDensidadeCorporal.setText(String.format("%.2f",this.antro.getDensidadeCorporal()));
            txtPorcentagemGordura.setText(String.format("%.2f",this.antro.getPorcentagemGordura()));
            this.antro.setPesoGordura();
            txtPesoGordura1.setText(String.format("%.2f",this.antro.getPesoGordura()));
            this.antro.setPesoMassaMagra();
            txtPesoMassaMagra.setText(String.format("%.2f",this.antro.getPesoMassaMagra()));
        }
        if(cmbTipoCalculo.getSelectedItem() == "Tecnica Guedes")
        {
            if(this.paciente.getSexo().equals("Masculino"))
            {
                this.antro.guedes(0);
                txtDensidadeCorporal.setText(String.format("%.2f",this.antro.getDensidadeCorporal()));
                txtPorcentagemGordura.setText(String.format("%.2f",this.antro.getPorcentagemGordura()));
                this.antro.setPesoGordura();
                txtPesoGordura1.setText(String.format("%.2f",this.antro.getPesoGordura()));
                this.antro.setPesoMassaMagra();
                txtPesoMassaMagra.setText(String.format("%.2f",this.antro.getPesoMassaMagra()));
            }
            else
            {
                this.antro.guedes(1);
                txtDensidadeCorporal.setText(String.format("%.2f",this.antro.getDensidadeCorporal()));
                txtPorcentagemGordura.setText(String.format("%.2f",this.antro.getPorcentagemGordura()));
                this.antro.setPesoGordura();
                txtPesoGordura1.setText(String.format("%.2f",this.antro.getPesoGordura()));
                this.antro.setPesoMassaMagra();
                txtPesoMassaMagra.setText(String.format("%.2f",this.antro.getPesoMassaMagra()));
            }
        }
        if(cmbTipoCalculo.getSelectedItem() == "Tecnica Lohman")
        {
            this.antro.lohman(this.idade);
            txtDensidadeCorporal.setText(String.format("%.2f",this.antro.getDensidadeCorporal()));
            txtPorcentagemGordura.setText(String.format("%.2f",this.antro.getPorcentagemGordura()));
            this.antro.setPesoGordura();
            txtPesoGordura1.setText(String.format("%.2f",this.antro.getPesoGordura()));
            this.antro.setPesoMassaMagra();
            txtPesoMassaMagra.setText(String.format("%.2f",this.antro.getPesoMassaMagra()));
        }
        if(cmbTipoCalculo.getSelectedItem() == "Tecnica Faulkner")
        {
            this.antro.faulkner();
            txtPorcentagemGordura.setText(String.format("%.2f",this.antro.getPorcentagemGordura()));
            this.antro.setPesoGordura();
            txtPesoGordura1.setText(String.format("%.2f",this.antro.getPesoGordura()));
            this.antro.setPesoMassaMagra();
            txtPesoMassaMagra.setText(String.format("%.2f",this.antro.getPesoMassaMagra()));
        }
        if(cmbTipoCalculo.getSelectedItem() == "Tecnica Pollock")
        {
            this.antro.poll();
            txtDensidadeCorporal.setText(String.format("%.2f",this.antro.getDensidadeCorporal()));
            txtPorcentagemGordura.setText(String.format("%.2f",this.antro.getPorcentagemGordura()));
            this.antro.setPesoGordura();
            txtPesoGordura1.setText(String.format("%.2f",this.antro.getPesoGordura()));
            this.antro.setPesoMassaMagra();
            txtPesoMassaMagra.setText(String.format("%.2f",this.antro.getPesoMassaMagra()));
        }
        if(cmbTipoCalculo.getSelectedItem() == "Tecnica de Slaughter Maior 35MM")
        {
            if(this.paciente.getSexo().equals("Masculino"))
            {
                this.antro.tecnicaSlaugtherMaior35(0);
                txtDensidadeCorporal.setText(String.format("%.2f",this.antro.getDensidadeCorporal()));
                txtPesoGordura1.setText(String.format("%.2f",this.antro.getPorcentagemGordura()));
                this.antro.setPesoMassaMagra();
                txtPesoMassaMagra.setText(String.format("%.2f",this.antro.getPesoMassaMagra()));
            }
            else
            {
                this.antro.tecnicaSlaugtherMaior35(1);
                txtDensidadeCorporal.setText(String.format("%.2f",this.antro.getDensidadeCorporal()));
                txtPesoGordura1.setText(String.format("%.2f",this.antro.getPorcentagemGordura()));
                this.antro.setPesoMassaMagra();
                txtPesoMassaMagra.setText(String.format("%.2f",this.antro.getPesoMassaMagra()));
            }
        }
        if(cmbTipoCalculo.getSelectedItem() == "Tecnica de Slaughter Menor 35MM")
        {
            int Const = Integer.parseInt(JOptionPane.showInputDialog(null, "Digite a Constante: "));
            if(this.paciente.getSexo().equals("Masculino"))
            {
                this.antro.tecnicaSlaugtherMenor35(0,Const);
                txtDensidadeCorporal.setText(String.valueOf(this.antro.getDensidadeCorporal()));
            }
            else
            {
                this.antro.tecnicaSlaugtherMenor35(1,Const);
                txtDensidadeCorporal.setText(String.valueOf(this.antro.getDensidadeCorporal()));
            }
        }
        if(cmbTipoCalculo.getSelectedItem() == "Tecnica Boileau")// if qual constante
        {
           int Const = Integer.parseInt(JOptionPane.showInputDialog(null, "Digite a Constante: "));
           this.antro.tecnicaBoileau(Const);
           txtPorcentagemGordura.setText(String.format("%.2f",this.antro.getPorcentagemGordura()));
           this.antro.setPesoGordura();
           txtPesoGordura1.setText(String.format("%.2f",this.antro.getPesoGordura()));
           this.antro.setPesoMassaMagra();
            txtPesoMassaMagra.setText(String.format("%.2f",this.antro.getPesoMassaMagra()));
        }       
        if(cmbTipoCalculo.getSelectedItem() == "Tecnica Jackson e Pollock e Ward")
        {
            this.antro.jackPollWard(this.idade);
            txtDensidadeCorporal.setText(String.format("%.2f",this.antro.getDensidadeCorporal()));
            txtPorcentagemGordura.setText(String.format("%.2f",this.antro.getPorcentagemGordura()));
            this.antro.setPesoGordura();
            txtPesoGordura1.setText(String.format("%.2f",this.antro.getPesoGordura()));
            this.antro.setPesoMassaMagra();
            txtPesoMassaMagra.setText(String.format("%.2f",this.antro.getPesoMassaMagra()));
        }
        if(cmbTipoCalculo.getSelectedItem() == "Tecnica Jackson e Pollock e Ward (Atletas)")// if qual constante
        {
            this.antro.jackPollWardAtletas(this.idade);
            txtDensidadeCorporal.setText(String.format("%.2f",this.antro.getDensidadeCorporal()));
            txtPorcentagemGordura.setText(String.format("%.2f",this.antro.getPorcentagemGordura()));
            this.antro.setPesoGordura();
            txtPesoGordura1.setText(String.format("%.2f",this.antro.getPesoGordura()));
            this.antro.setPesoMassaMagra();
            txtPesoMassaMagra.setText(String.format("%.2f",this.antro.getPesoMassaMagra()));
        }       
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void cmbTipoCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoCalculoActionPerformed
        // TODO add your handling code here:
        iniciar();
        if(cmbTipoCalculo.getSelectedItem() == "Tecnica Jackson e Pollock 3 Dobras")
        {
            txtPeito.setEnabled(true);
            txtAbdominal.setEnabled(true);
            txtCoxa.setEnabled(true);
            txtTriceps.setEnabled(false);
            txtSubescapular.setEnabled(false);
            txtCircAbdominal.setEnabled(false);
            txtCircPerna.setEnabled(false);
            txtCircBraco.setEnabled(false);
            txtCircPanturrilha.setEnabled(false);
            txtSuprailiaca.setEnabled(false);
            txtAxiliarMedia.setEnabled(false);
        } 
        if(cmbTipoCalculo.getSelectedItem() == "Tecnica Jackson e Pollock 7 Dobras")
        {
            txtPeito.setEnabled(true);
            txtAbdominal.setEnabled(true);
            txtCoxa.setEnabled(true);
            txtTriceps.setEnabled(true);
            txtSubescapular.setEnabled(true);
            txtCircAbdominal.setEnabled(false);
            txtCircPerna.setEnabled(false);
            txtCircBraco.setEnabled(false);
            txtCircPanturrilha.setEnabled(false);
            txtSuprailiaca.setEnabled(true);
            txtAxiliarMedia.setEnabled(true);            
        }
        if(cmbTipoCalculo.getSelectedItem() == "Tecnica Guedes")
        {
            if(this.paciente.getSexo().equals("Masculino"))
            {
                txtPeito.setEnabled(false);
                txtAbdominal.setEnabled(true);
                txtCoxa.setEnabled(false);
                txtTriceps.setEnabled(true);
                txtSubescapular.setEnabled(false);
                txtCircAbdominal.setEnabled(false);
                txtCircPerna.setEnabled(false);
                txtCircBraco.setEnabled(false);
                txtCircPanturrilha.setEnabled(false);
                txtSuprailiaca.setEnabled(true);
                txtAxiliarMedia.setEnabled(false);
            }
            else
            {
                txtPeito.setEnabled(false);
                txtAbdominal.setEnabled(false);
                txtCoxa.setEnabled(true);
                txtTriceps.setEnabled(false);
                txtSubescapular.setEnabled(true);
                txtCircAbdominal.setEnabled(false);
                txtCircPerna.setEnabled(false);
                txtCircBraco.setEnabled(false);
                txtCircPanturrilha.setEnabled(false);
                txtSuprailiaca.setEnabled(true);
                txtAxiliarMedia.setEnabled(false);
            }
        }
        if(cmbTipoCalculo.getSelectedItem() == "Tecnica Lohman")
        {
            txtPeito.setEnabled(false);
            txtAbdominal.setEnabled(false);
            txtCoxa.setEnabled(false);
            txtTriceps.setEnabled(true);
            txtSubescapular.setEnabled(true);
            txtCircAbdominal.setEnabled(true);
            txtCircPerna.setEnabled(false);
            txtCircBraco.setEnabled(false);
            txtCircPanturrilha.setEnabled(false);
            txtSuprailiaca.setEnabled(false);
            txtAxiliarMedia.setEnabled(false);
        }
        if(cmbTipoCalculo.getSelectedItem() == "Tecnica Faulkner")
        {
            txtPeito.setEnabled(false);
            txtAbdominal.setEnabled(true);
            txtCoxa.setEnabled(false);
            txtTriceps.setEnabled(true);
            txtSubescapular.setEnabled(true);
            txtCircAbdominal.setEnabled(false);
            txtCircPerna.setEnabled(false);
            txtCircBraco.setEnabled(false);
            txtCircPanturrilha.setEnabled(false);
            txtSuprailiaca.setEnabled(true);
            txtAxiliarMedia.setEnabled(false);
        }
        if(cmbTipoCalculo.getSelectedItem() == "Tecnica Pollock")
        {
            txtPeito.setEnabled(true);
            txtAbdominal.setEnabled(false);
            txtCoxa.setEnabled(true);
            txtTriceps.setEnabled(false);
            txtSubescapular.setEnabled(true);
            txtCircAbdominal.setEnabled(false);
            txtCircPerna.setEnabled(false);
            txtCircBraco.setEnabled(false);
            txtCircPanturrilha.setEnabled(false);
            txtSuprailiaca.setEnabled(false);
            txtAxiliarMedia.setEnabled(false);
        }
        
        if(cmbTipoCalculo.getSelectedItem() == "Tecnica de Slaughter Maior 35MM")
        {
            txtPeito.setEnabled(false);
            txtAbdominal.setEnabled(false);
            txtCoxa.setEnabled(false);
            txtTriceps.setEnabled(true);
            txtSubescapular.setEnabled(true);
            txtCircAbdominal.setEnabled(false);
            txtCircPerna.setEnabled(false);
            txtCircBraco.setEnabled(false);
            txtCircPanturrilha.setEnabled(false);
            txtSuprailiaca.setEnabled(false);
            txtAxiliarMedia.setEnabled(false);
        }
        if(cmbTipoCalculo.getSelectedItem() == "Tecnica de Slaughter Menor 35MM")
        {            
            txtPeito.setEnabled(false);
            txtAbdominal.setEnabled(false);
            txtCoxa.setEnabled(false);
            txtTriceps.setEnabled(true);
            txtSubescapular.setEnabled(true);
            txtCircAbdominal.setEnabled(false);
            txtCircPerna.setEnabled(false);
            txtCircBraco.setEnabled(false);
            txtCircPanturrilha.setEnabled(false);
            txtSuprailiaca.setEnabled(false);
            txtAxiliarMedia.setEnabled(false);
        }
        if(cmbTipoCalculo.getSelectedItem() == "Tecnica Boileau")// if qual constante
        {            
            txtPeito.setEnabled(false);
            txtAbdominal.setEnabled(false);
            txtCoxa.setEnabled(false);
            txtTriceps.setEnabled(true);
            txtSubescapular.setEnabled(true);
            txtCircAbdominal.setEnabled(false);
            txtCircPerna.setEnabled(false);
            txtCircBraco.setEnabled(false);
            txtCircPanturrilha.setEnabled(false);
            txtSuprailiaca.setEnabled(false);
            txtAxiliarMedia.setEnabled(false);
        }
        
        if(cmbTipoCalculo.getSelectedItem() == "Tecnica Jackson e Pollock e Ward")
        {
            txtPeito.setEnabled(false);
            txtAbdominal.setEnabled(false);
            txtCoxa.setEnabled(true);
            txtTriceps.setEnabled(true);
            txtSubescapular.setEnabled(false);
            txtCircAbdominal.setEnabled(false);
            txtCircPerna.setEnabled(false);
            txtCircBraco.setEnabled(false);
            txtCircPanturrilha.setEnabled(false);
            txtSuprailiaca.setEnabled(true);
            txtAxiliarMedia.setEnabled(false);
        }
        if(cmbTipoCalculo.getSelectedItem() == "Tecnica Jackson e Pollock e Ward (Atletas)")// if qual constante
        {
            txtPeito.setEnabled(false);
            txtAbdominal.setEnabled(false);
            txtCoxa.setEnabled(true);
            txtTriceps.setEnabled(true);
            txtSubescapular.setEnabled(false);
            txtCircAbdominal.setEnabled(false);
            txtCircPerna.setEnabled(false);
            txtCircBraco.setEnabled(false);
            txtCircPanturrilha.setEnabled(false);
            txtSuprailiaca.setEnabled(true);
            txtAxiliarMedia.setEnabled(false);
        }
    }//GEN-LAST:event_cmbTipoCalculoActionPerformed

    private void txtimcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtimcActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtimcActionPerformed

    private void txtPesoAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoAtualActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtPesoAtualActionPerformed

    private void txtEstaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstaturaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtEstaturaActionPerformed

    private void txtEstaturaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstaturaKeyReleased
        // TODO add your handling code here:
                this.antro.setEstatura(Double.valueOf(txtEstatura.getText())); 
        if(txtPesoAtual.getText() != "")
        {
            this.antro.setImc();
            double x = this.antro.getImc();
            txtimc.setText(String.format("%.2f", x ));
        }
    }//GEN-LAST:event_txtEstaturaKeyReleased

    private void txtPesoAtualKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesoAtualKeyReleased
        // TODO add your handling code here:
                this.antro.setPeso(Double.valueOf(txtPesoAtual.getText()));
        if(txtEstatura.getText()!="")
        {
            this.antro.setImc();
            double x = this.antro.getImc();
            txtimc.setText(String.format("%.2f", x )); 
        }
    }//GEN-LAST:event_txtPesoAtualKeyReleased

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        try
        {
            this.antro.setIdAntro(antroDao.Max()+ 1); 
            this.antro.setPaciente(this.paciente);
            this.antro.setData(Integer.parseInt(txtData.getText()));
            antroDao.create(this.antro);
            JOptionPane.showMessageDialog(this, "Paciente Inserido com sucesso!");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(antropometria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(antropometria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(antropometria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(antropometria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Paciente p = new Paciente();
                new antropometria(p).setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbTipoCalculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JTextField txtAbdominal;
    private javax.swing.JTextField txtAdequacaoPeso;
    private javax.swing.JTextField txtAjustePesoIdeal;
    private javax.swing.JTextField txtAxiliarMedia;
    private javax.swing.JTextField txtCircAbdominal;
    private javax.swing.JTextField txtCircBraco;
    private javax.swing.JTextField txtCircPanturrilha;
    private javax.swing.JTextField txtCircPerna;
    private javax.swing.JTextField txtClassificacaoAdequacaoPeso;
    private javax.swing.JTextField txtCoxa;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtDensidadeCorporal;
    private javax.swing.JTextField txtEstatura;
    private javax.swing.JTextField txtPeito;
    private javax.swing.JTextField txtPesoAtual;
    private javax.swing.JTextField txtPesoGordura1;
    private javax.swing.JTextField txtPesoIdeal;
    private javax.swing.JTextField txtPesoMassaMagra;
    private javax.swing.JTextField txtPorcentagemGordura;
    private javax.swing.JTextField txtSubescapular;
    private javax.swing.JTextField txtSuprailiaca;
    private javax.swing.JTextField txtTriceps;
    private javax.swing.JTextField txtimc;
    // End of variables declaration//GEN-END:variables
}
