/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import beans.Dieta;
import beans.Paciente;
import controladores.DietaJpaController;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

/**
 *
 * @author Leonardo Vasconcelos
 */
public class dietaSemanal extends javax.swing.JFrame {
    private Paciente paciente = new Paciente();
    private DietaJpaController dietaDao;
    /**
     * Creates new form dietaSemanal
     */
    private void preencherCombo()
    {
        if( dietaDao.conta(this.paciente) > 0)
        {
            int n = dietaDao.conta(this.paciente);
            n = n/7;
            for(int i=0; i <= n ; i++)
            {
                if(i==0)
                {
                    cbmSemana.addItem("novo");  
                }
                else
                {
                    cbmSemana.addItem(String.valueOf(i));
                }
                
            }
        }else
        {
            cbmSemana.addItem("novo"); 
        }
    }
    public dietaSemanal(Paciente p) {
        initComponents();
        this.dietaDao = new DietaJpaController(Persistence.createEntityManagerFactory("NutriMaisPU"));
        this.paciente = p;
        lblId.setText(String.valueOf(p.getIdPaciente()));
        lblNome.setText(p.getNome());
        preencherCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtSexLM = new javax.swing.JTextPane();
        jScrollPane33 = new javax.swing.JScrollPane();
        txtTerJa = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtTerLM = new javax.swing.JTextPane();
        jScrollPane32 = new javax.swing.JScrollPane();
        txtSabCe = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtSegLM = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtSabLM = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtQuarLM = new javax.swing.JTextPane();
        jScrollPane36 = new javax.swing.JScrollPane();
        txtTerCe = new javax.swing.JTextPane();
        jScrollPane35 = new javax.swing.JScrollPane();
        txtSegCe = new javax.swing.JTextPane();
        jScrollPane34 = new javax.swing.JScrollPane();
        txtDomCe = new javax.swing.JTextPane();
        jScrollPane16 = new javax.swing.JScrollPane();
        txtQuarAl = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtQuinLM = new javax.swing.JTextPane();
        jScrollPane27 = new javax.swing.JScrollPane();
        txtSexAl = new javax.swing.JTextPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        txtSegCM = new javax.swing.JTextPane();
        jScrollPane28 = new javax.swing.JScrollPane();
        txtQuinLT = new javax.swing.JTextPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        txtDomCM = new javax.swing.JTextPane();
        jScrollPane15 = new javax.swing.JScrollPane();
        txtQuinAl = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane31 = new javax.swing.JScrollPane();
        txtSexCe = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane29 = new javax.swing.JScrollPane();
        txtQuinJa = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane30 = new javax.swing.JScrollPane();
        txtQuarJa = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane42 = new javax.swing.JScrollPane();
        txtQuinCe = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSabCM = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        jScrollPane22 = new javax.swing.JScrollPane();
        txtTerLT = new javax.swing.JTextPane();
        cbmSemana = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane24 = new javax.swing.JScrollPane();
        txtQuarLT = new javax.swing.JTextPane();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane23 = new javax.swing.JScrollPane();
        txtDomAl = new javax.swing.JTextPane();
        jScrollPane26 = new javax.swing.JScrollPane();
        txtSegAl = new javax.swing.JTextPane();
        jScrollPane25 = new javax.swing.JScrollPane();
        txtSabAl = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane37 = new javax.swing.JScrollPane();
        txtDomJa = new javax.swing.JTextPane();
        jScrollPane38 = new javax.swing.JScrollPane();
        txtQuarCe = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtTerCM = new javax.swing.JTextPane();
        jScrollPane39 = new javax.swing.JScrollPane();
        txtSabJa = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtDomLM = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtQuinCM = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtQuarCM = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSexCM = new javax.swing.JTextPane();
        jScrollPane17 = new javax.swing.JScrollPane();
        txtSexLT = new javax.swing.JTextPane();
        jScrollPane18 = new javax.swing.JScrollPane();
        txtSabLT = new javax.swing.JTextPane();
        jScrollPane19 = new javax.swing.JScrollPane();
        txtTerAl = new javax.swing.JTextPane();
        jScrollPane20 = new javax.swing.JScrollPane();
        txtDomLT = new javax.swing.JTextPane();
        jScrollPane21 = new javax.swing.JScrollPane();
        txtSegLT = new javax.swing.JTextPane();
        jScrollPane40 = new javax.swing.JScrollPane();
        txtSegJa = new javax.swing.JTextPane();
        jScrollPane41 = new javax.swing.JScrollPane();
        txtSexJa = new javax.swing.JTextPane();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(184, 225, 206));

        jScrollPane11.setViewportView(txtSexLM);

        jScrollPane33.setViewportView(txtTerJa);

        jScrollPane8.setViewportView(txtTerLM);

        jScrollPane32.setViewportView(txtSabCe);

        jScrollPane7.setViewportView(txtSegLM);

        jScrollPane10.setViewportView(txtSabLM);

        jScrollPane9.setViewportView(txtQuarLM);

        jScrollPane36.setViewportView(txtTerCe);

        jScrollPane35.setViewportView(txtSegCe);

        jScrollPane34.setViewportView(txtDomCe);

        jScrollPane16.setViewportView(txtQuarAl);

        jScrollPane12.setViewportView(txtQuinLM);

        jScrollPane27.setViewportView(txtSexAl);

        jScrollPane13.setViewportView(txtSegCM);

        jScrollPane28.setViewportView(txtQuinLT);

        jScrollPane14.setViewportView(txtDomCM);

        jScrollPane15.setViewportView(txtQuinAl);

        jLabel9.setText("Sábado");

        jScrollPane31.setViewportView(txtSexCe);

        jLabel8.setText("Sexta");

        jLabel5.setText("Segunda");

        jScrollPane29.setViewportView(txtQuinJa);

        jLabel4.setText("Terça");

        jLabel7.setText("Quinta");

        jScrollPane30.setViewportView(txtQuarJa);

        jLabel6.setText("Quarta");

        jScrollPane42.setViewportView(txtQuinCe);

        jLabel3.setText("Domingo");

        jScrollPane1.setViewportView(txtSabCM);

        jLabel2.setText("ID:");

        lblId.setText("????");

        jLabel1.setText("Nome:");

        lblNome.setText("????");

        jScrollPane22.setViewportView(txtTerLT);

        cbmSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmSemanaActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forms/1480536385_seo-social-web-network-internet_130.png"))); // NOI18N
        jButton1.setText("Selecione");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane24.setViewportView(txtQuarLT);

        jLabel16.setText("Semana:");

        jLabel15.setText("Ceia");

        jScrollPane23.setViewportView(txtDomAl);

        jScrollPane26.setViewportView(txtSegAl);

        jScrollPane25.setViewportView(txtSabAl);

        jLabel10.setText("Café da Manhã");

        jLabel14.setText("Janta");

        jLabel13.setText("Lanche da Tarde");

        jLabel12.setText("Almoço");

        jLabel11.setText("Lanche da Manhã");

        jScrollPane37.setViewportView(txtDomJa);

        jScrollPane38.setViewportView(txtQuarCe);

        jScrollPane5.setViewportView(txtTerCM);

        jScrollPane39.setViewportView(txtSabJa);

        jScrollPane6.setViewportView(txtDomLM);

        jScrollPane3.setViewportView(txtQuinCM);

        jScrollPane4.setViewportView(txtQuarCM);

        jScrollPane2.setViewportView(txtSexCM);

        jScrollPane17.setViewportView(txtSexLT);

        jScrollPane18.setViewportView(txtSabLT);

        jScrollPane19.setViewportView(txtTerAl);

        jScrollPane20.setViewportView(txtDomLT);

        jScrollPane21.setViewportView(txtSegLT);

        jScrollPane40.setViewportView(txtSegJa);

        jScrollPane41.setViewportView(txtSexJa);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forms/recycle.png"))); // NOI18N
        jButton4.setText("Excluir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forms/1480533971_BT_save.png"))); // NOI18N
        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forms/nutrimaisReduzidoReduzido.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jScrollPane37, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane40, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane33, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane29, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane41, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane39, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane34, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane35, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane36, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane38, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane42, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane31, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane32, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(22, 22, 22))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNome)
                                .addGap(66, 66, 66)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblId)
                                .addGap(94, 94, 94)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbmSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(jLabel3)
                                .addGap(65, 65, 65)
                                .addComponent(jLabel5)
                                .addGap(71, 71, 71)
                                .addComponent(jLabel4)
                                .addGap(63, 63, 63)
                                .addComponent(jLabel6)
                                .addGap(77, 77, 77)
                                .addComponent(jLabel7)
                                .addGap(67, 67, 67)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(61, 61, 61))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(314, 314, 314)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNome)
                    .addComponent(jLabel2)
                    .addComponent(lblId)
                    .addComponent(jLabel16)
                    .addComponent(jButton1)
                    .addComponent(cbmSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel10)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel11)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel12)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel13)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane39, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane41, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane29, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane33, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane40, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane37, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(51, 51, 51)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane34, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane35, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane36, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane38, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane32, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane31, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane42, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel15)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4))
                    .addComponent(jLabel17))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Dieta[] d = new Dieta[7];
        int id = dietaDao.getDietaCount()+1;
        
        d[0] = new Dieta();
        d[0].setDia("Segunda");
        d[0].setCafeDaManha(txtSegCM.getText());
        d[0].setLancheDaManha(txtSegLM.getText());
        d[0].setAlmoco(txtSegAl.getText());
        d[0].setLancheDaTarde(txtSegLT.getText());
        d[0].setJantar(txtSegJa.getText());
        d[0].setCeia(txtSegCe.getText());
        
        d[1] = new Dieta();
        d[1].setDia("Terça");
        d[1].setCafeDaManha(txtTerCM.getText());
        d[1].setLancheDaManha(txtTerLM.getText());
        d[1].setAlmoco(txtTerAl.getText());
        d[1].setLancheDaTarde(txtTerLT.getText());
        d[1].setJantar(txtTerJa.getText());
        d[1].setCeia(txtTerCe.getText());
        
        d[2] = new Dieta();
        d[2].setDia("Quarta");
        d[2].setCafeDaManha(txtQuarCM.getText());
        d[2].setLancheDaManha(txtQuarLM.getText());
        d[2].setAlmoco(txtQuarAl.getText());
        d[2].setLancheDaTarde(txtQuarLT.getText());
        d[2].setJantar(txtQuarJa.getText());
        d[2].setCeia(txtQuarCe.getText());
        
        d[3] = new Dieta();
        d[3].setDia("Quinta");
        d[3].setCafeDaManha(txtQuinCM.getText());
        d[3].setLancheDaManha(txtQuinLM.getText());
        d[3].setAlmoco(txtQuinAl.getText());
        d[3].setLancheDaTarde(txtQuinLT.getText());
        d[3].setJantar(txtQuinJa.getText());
        d[3].setCeia(txtQuinCe.getText());
        
        d[4] = new Dieta();
        d[4].setDia("Sexta");
        d[4].setCafeDaManha(txtSexCM.getText());
        d[4].setLancheDaManha(txtSegLM.getText());
        d[4].setAlmoco(txtSexAl.getText());
        d[4].setLancheDaTarde(txtSexLT.getText());
        d[4].setJantar(txtSexJa.getText());
        d[4].setCeia(txtSexCe.getText());
        
        d[5] = new Dieta();
        d[5].setDia("Sabado");
        d[5].setCafeDaManha(txtSabCM.getText());
        d[5].setLancheDaManha(txtSabLM.getText());
        d[5].setAlmoco(txtSabAl.getText());
        d[5].setLancheDaTarde(txtSabLT.getText());
        d[5].setJantar(txtSabJa.getText());
        d[5].setCeia(txtSabCe.getText());
        
        d[6] = new Dieta();
        d[6].setDia("Domigo");
        d[6].setCafeDaManha(txtDomCM.getText());
        d[6].setLancheDaManha(txtDomLM.getText());
        d[6].setAlmoco(txtDomAl.getText());
        d[6].setLancheDaTarde(txtDomLT.getText());
        d[6].setJantar(txtDomJa.getText());
        d[6].setCeia(txtDomCe.getText());
        
        if(cbmSemana.getSelectedItem().equals("Novo")) 
        {
           try
            {
                for(int i=0;i<=6;i++)
                { 
                    d[i].setIdDieta(id); 
                    d[i].setPaciente(this.paciente);
                    dietaDao.create(d[i]);
                }                
                JOptionPane.showMessageDialog(this, "Dieta Inserida com sucesso!");
                preencherCombo();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
        else
        {
            try
            {
                for(int i=0;i<=6;i++)
                { 
                    d[i].setIdDieta(id); 
                    d[i].setPaciente(this.paciente);
                    dietaDao.edit(d[i]);
                }                
                JOptionPane.showMessageDialog(this, "Dieta Atualizada com sucesso!");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbmSemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmSemanaActionPerformed
        // TODO add your handling code here:
        List<Dieta> di = new ArrayList();
        Dieta[] d = new Dieta[7];
        String s = String.valueOf(cbmSemana.getSelectedItem());
        if(!s.equals("Novo"))
        {
            try
            {
                di.add(dietaDao.findDietaByIdDia(Integer.parseInt(s),"Segunda"));
                di.add(dietaDao.findDietaByIdDia(Integer.parseInt(s),"Terça"));
                di.add(dietaDao.findDietaByIdDia(Integer.parseInt(s),"Quarta"));
                di.add(dietaDao.findDietaByIdDia(Integer.parseInt(s),"Quinta"));
                di.add(dietaDao.findDietaByIdDia(Integer.parseInt(s),"Sexta"));
                di.add(dietaDao.findDietaByIdDia(Integer.parseInt(s),"Sabado"));
                di.add(dietaDao.findDietaByIdDia(Integer.parseInt(s),"Domingo"));
                
                txtSegCM.setText(di.get(0).getCafeDaManha());
                txtSegLM.setText(di.get(0).getLancheDaManha());
                txtSegAl.setText(di.get(0).getAlmoco());
                txtSegLT.setText(di.get(0).getLancheDaTarde());
                txtSegJa.setText(di.get(0).getJantar());
                txtSegCe.setText(di.get(0).getCeia());
     
                txtTerCM.setText(di.get(1).getCafeDaManha());
                txtTerLM.setText(di.get(1).getLancheDaManha());
                txtTerAl.setText(di.get(1).getAlmoco());
                txtTerLT.setText(di.get(1).getLancheDaTarde());
                txtTerJa.setText(di.get(1).getJantar());
                txtTerCe.setText(di.get(1).getCeia());
   
                txtQuarCM.setText(di.get(2).getCafeDaManha());
                txtQuarLM.setText(di.get(2).getLancheDaManha());
                txtQuarAl.setText(di.get(2).getAlmoco());
                txtQuarLT.setText(di.get(2).getLancheDaTarde());
                txtQuarJa.setText(di.get(2).getJantar());
                txtQuarCe.setText(di.get(2).getCeia());
               
                txtQuinCM.setText(di.get(3).getCafeDaManha());
                txtQuinLM.setText(di.get(3).getLancheDaManha());
                txtQuinAl.setText(di.get(3).getAlmoco());
                txtQuinLT.setText(di.get(3).getLancheDaTarde());
                txtQuinJa.setText(di.get(3).getJantar());
                txtQuinCe.setText(di.get(3).getCeia());
                
                txtSexCM.setText(di.get(4).getCafeDaManha());
                txtSexLM.setText(di.get(4).getLancheDaManha());
                txtSexAl.setText(di.get(4).getAlmoco());
                txtSexLT.setText(di.get(4).getLancheDaTarde());
                txtSexJa.setText(di.get(4).getJantar());
                txtSexCe.setText(di.get(4).getCeia());
                
                txtSabCM.setText(di.get(5).getCafeDaManha());
                txtSabLM.setText(di.get(5).getLancheDaManha());
                txtSabAl.setText(di.get(5).getAlmoco());
                txtSabLT.setText(di.get(5).getLancheDaTarde());
                txtSabJa.setText(di.get(5).getJantar());
                txtSabCe.setText(di.get(5).getCeia());
                
                txtDomCM.setText(di.get(6).getCafeDaManha());
                txtDomLM.setText(di.get(6).getLancheDaManha());
                txtDomAl.setText(di.get(6).getAlmoco());
                txtDomLT.setText(di.get(6).getLancheDaTarde());
                txtDomJa.setText(di.get(6).getJantar());
                txtDomCe.setText(di.get(6).getCeia());
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_cbmSemanaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try
            {
                String s = String.valueOf(cbmSemana.getSelectedItem());
                dietaDao.apaga(Integer.parseInt(s),this.paciente);              
                JOptionPane.showMessageDialog(this, "Dieta apagada com sucesso!");
                preencherCombo();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dietaSemanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dietaSemanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dietaSemanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dietaSemanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Paciente paciente = new Paciente();
                new dietaSemanal(paciente).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbmSemana;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JScrollPane jScrollPane31;
    private javax.swing.JScrollPane jScrollPane32;
    private javax.swing.JScrollPane jScrollPane33;
    private javax.swing.JScrollPane jScrollPane34;
    private javax.swing.JScrollPane jScrollPane35;
    private javax.swing.JScrollPane jScrollPane36;
    private javax.swing.JScrollPane jScrollPane37;
    private javax.swing.JScrollPane jScrollPane38;
    private javax.swing.JScrollPane jScrollPane39;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane40;
    private javax.swing.JScrollPane jScrollPane41;
    private javax.swing.JScrollPane jScrollPane42;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextPane txtDomAl;
    private javax.swing.JTextPane txtDomCM;
    private javax.swing.JTextPane txtDomCe;
    private javax.swing.JTextPane txtDomJa;
    private javax.swing.JTextPane txtDomLM;
    private javax.swing.JTextPane txtDomLT;
    private javax.swing.JTextPane txtQuarAl;
    private javax.swing.JTextPane txtQuarCM;
    private javax.swing.JTextPane txtQuarCe;
    private javax.swing.JTextPane txtQuarJa;
    private javax.swing.JTextPane txtQuarLM;
    private javax.swing.JTextPane txtQuarLT;
    private javax.swing.JTextPane txtQuinAl;
    private javax.swing.JTextPane txtQuinCM;
    private javax.swing.JTextPane txtQuinCe;
    private javax.swing.JTextPane txtQuinJa;
    private javax.swing.JTextPane txtQuinLM;
    private javax.swing.JTextPane txtQuinLT;
    private javax.swing.JTextPane txtSabAl;
    private javax.swing.JTextPane txtSabCM;
    private javax.swing.JTextPane txtSabCe;
    private javax.swing.JTextPane txtSabJa;
    private javax.swing.JTextPane txtSabLM;
    private javax.swing.JTextPane txtSabLT;
    private javax.swing.JTextPane txtSegAl;
    private javax.swing.JTextPane txtSegCM;
    private javax.swing.JTextPane txtSegCe;
    private javax.swing.JTextPane txtSegJa;
    private javax.swing.JTextPane txtSegLM;
    private javax.swing.JTextPane txtSegLT;
    private javax.swing.JTextPane txtSexAl;
    private javax.swing.JTextPane txtSexCM;
    private javax.swing.JTextPane txtSexCe;
    private javax.swing.JTextPane txtSexJa;
    private javax.swing.JTextPane txtSexLM;
    private javax.swing.JTextPane txtSexLT;
    private javax.swing.JTextPane txtTerAl;
    private javax.swing.JTextPane txtTerCM;
    private javax.swing.JTextPane txtTerCe;
    private javax.swing.JTextPane txtTerJa;
    private javax.swing.JTextPane txtTerLM;
    private javax.swing.JTextPane txtTerLT;
    // End of variables declaration//GEN-END:variables
}
